version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "443:443"
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
