version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - app_network

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    networks:
      app_network:
        ipv4_address: 172.21.0.4

networks:
  app_network:
    ipam:
      config:
        - subnet: 172.21.0.0/16
